server:
  port: 8088

spring:
  application:
    name: daily-quiz-0715

  thymeleaf:
    cache: false # 캐시를 사용하지 않음 -> 수정 시 바로 반영됨
    prefix: classpath:/templates/ # 템플릿 파일 위치
    suffix: .html # 템플릿 파일 확장자
    mode: HTML # HTML5 호환
    encoding: UTF-8 # 인코딩 설정